const express=require('express');const path=require('path');const crypto=require('crypto');const {Pool}=require('pg');
const app=express(),PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined,max:Number(process.env.DB_POOL_MAX||5),idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
const ready=(async()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');await pool.query(`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,gender TEXT NOT NULL DEFAULT 'Unisex',price INTEGER NOT NULL CHECK(price>0),rating REAL NOT NULL DEFAULT 5,image TEXT NOT NULL,description TEXT DEFAULT '',stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),sizes TEXT NOT NULL DEFAULT '6,7,8,9,10,11,12',created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,customer_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT DEFAULT '',address TEXT NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'Pending',created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY,order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER NOT NULL REFERENCES products(id),size INTEGER NOT NULL,qty INTEGER NOT NULL,price INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS offers(id SERIAL PRIMARY KEY,title TEXT NOT NULL,subtitle TEXT NOT NULL DEFAULT '',end_at TIMESTAMPTZ NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);`);})();
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
const secret=process.env.ADMIN_SESSION_SECRET;
function sign(v){return crypto.createHmac('sha256',secret||'missing-secret').update(v).digest('hex')}
function makeToken(){const exp=Date.now()+8*60*60*1000,v=String(exp);return `${v}.${sign(v)}`}
function validToken(token){if(!secret||!token)return false;const[a,b]=String(token).split('.');if(!a||!b||Number(a)<Date.now())return false;const sb=Buffer.from(sign(a));const tb=Buffer.from(b);return sb.length===tb.length&&crypto.timingSafeEqual(sb,tb)}
function cookie(req,name){const part=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return part?decodeURIComponent(part.slice(name.length+1)):''}
function adminOnly(req,res,next){if(validToken(cookie(req,'sv_admin')))return next();if(req.path==='/admin'||req.path==='/admin/')return res.redirect('/admin/login');return res.status(401).json({error:'Admin authentication required',login:'/admin/login'})}
const protectedApi=(req,res,next)=>{const adminOfferMutation=req.path.startsWith('/api/offers')&&req.method!=='GET';if(req.path.startsWith('/api/admin')||adminOfferMutation||(['POST','PUT','DELETE'].includes(req.method)&&req.path.startsWith('/api/products'))||(req.path==='/api/orders'&&req.method==='GET')||(req.path.startsWith('/api/orders/')&&req.method==='PUT')||req.path==='/api/stats')return adminOnly(req,res,next);next()};
app.use(async(req,res,next)=>{try{await ready;next()}catch(e){console.error(e);res.status(500).json({error:'Database unavailable. Check DATABASE_URL.'})}});
app.post('/api/admin/login',async(req,res)=>{if(!secret)return res.status(503).json({error:'ADMIN_SESSION_SECRET is not configured'});const password=String(req.body?.password||''),expected=String(process.env.ADMIN_PASSWORD||'');if(!expected)return res.status(503).json({error:'ADMIN_PASSWORD is not configured'});const a=Buffer.from(password),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Incorrect password'});res.setHeader('Set-Cookie',`sv_admin=${encodeURIComponent(makeToken())}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`);res.json({ok:true})});
app.post('/api/admin/logout',(req,res)=>{res.setHeader('Set-Cookie','sv_admin=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/admin/session',(req,res)=>res.json({authenticated:validToken(cookie(req,'sv_admin'))}));
app.get('/admin/login',(req,res)=>res.sendFile(path.join(__dirname,'public','admin-login.html')));
app.use(protectedApi);
app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'SoleVault',database:'postgres'})}catch(e){res.status(503).json({ok:false,error:'Database unavailable'})}});
app.get('/api/products',async(req,res)=>{try{const{category,gender,search,sort}=req.query,p=[];let q='SELECT * FROM products WHERE 1=1';if(category&&category!=='All'){p.push(category);q+=` AND category=$${p.length}`}if(gender&&gender!=='All'){p.push(gender);q+=` AND gender=$${p.length}`}if(search){p.push(`%${search}%`);const a=p.length;p.push(`%${search}%`);const b=p.length;p.push(`%${search}%`);const c=p.length;q+=` AND (name ILIKE $${a} OR category ILIKE $${b} OR gender ILIKE $${c})`}if(sort==='low')q+=' ORDER BY price ASC';else if(sort==='high')q+=' ORDER BY price DESC';else if(sort==='rating')q+=' ORDER BY rating DESC';else q+=' ORDER BY id DESC';res.json((await pool.query(q,p)).rows)}catch(e){res.status(500).json({error:'Unable to load products'})}});
app.get('/api/products/:id',async(req,res)=>{try{const r=await pool.query('SELECT * FROM products WHERE id=$1',[req.params.id]);r.rows[0]?res.json(r.rows[0]):res.status(404).json({error:'Product not found'})}catch(e){res.status(500).json({error:'Unable to load product'})}});
function validateProduct(x){const name=String(x.name||'').trim(),category=String(x.category||'').trim(),image=String(x.image||'').trim(),price=Number(x.price),rating=Number(x.rating??5),stock=Number(x.stock??0);if(!name||!category||!image||!Number.isFinite(price)||price<=0)return'Valid name, category, price and image are required';if(!Number.isFinite(rating)||rating<0||rating>5)return'Rating must be between 0 and 5';if(!Number.isInteger(stock)||stock<0)return'Stock must be a non-negative integer';return null}
app.post('/api/products',async(req,res)=>{const e=validateProduct(req.body);if(e)return res.status(400).json({error:e});try{const x=req.body,r=await pool.query(`INSERT INTO products(name,category,gender,price,rating,image,description,stock,sizes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[String(x.name).trim(),String(x.category).trim(),x.gender||'Unisex',Number(x.price),Number(x.rating??5),String(x.image).trim(),String(x.description||''),Number(x.stock??0),String(x.sizes||'6,7,8,9,10,11,12')]);res.status(201).json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:'Unable to create product'})}});
app.put('/api/products/:id',async(req,res)=>{try{const old=(await pool.query('SELECT * FROM products WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Product not found'});const x={...old,...req.body},e=validateProduct(x);if(e)return res.status(400).json({error:e});const r=await pool.query(`UPDATE products SET name=$1,category=$2,gender=$3,price=$4,rating=$5,image=$6,description=$7,stock=$8,sizes=$9 WHERE id=$10 RETURNING *`,[String(x.name).trim(),String(x.category).trim(),x.gender||'Unisex',Number(x.price),Number(x.rating),String(x.image).trim(),String(x.description||''),Number(x.stock),String(x.sizes||'6,7,8,9,10,11,12'),req.params.id]);res.json(r.rows[0])}catch(e){res.status(500).json({error:'Unable to update product'})}});
app.delete('/api/products/:id',async(req,res)=>{try{const r=await pool.query('DELETE FROM products WHERE id=$1',[req.params.id]);r.rowCount?res.json({ok:true}):res.status(404).json({error:'Product not found'})}catch(e){if(e.code==='23503')return res.status(409).json({error:'This product is used by an order and cannot be deleted.'});res.status(500).json({error:'Unable to delete product'})}});
function validOffer(x){const title=String(x.title||'').trim(),end=new Date(x.end_at);if(!title)return'Title is required';if(Number.isNaN(end.getTime())||end<=new Date())return'Offer end time must be in the future';return null}
app.get('/api/offers',async(req,res)=>{try{res.json((await pool.query(`SELECT * FROM offers WHERE active=TRUE AND end_at>NOW() ORDER BY end_at ASC`)).rows)}catch(e){res.status(500).json({error:'Unable to load offers'})}});
app.get('/api/admin/offers',async(req,res)=>{try{res.json((await pool.query('SELECT * FROM offers ORDER BY id DESC')).rows)}catch(e){res.status(500).json({error:'Unable to load offers'})}});
app.post('/api/offers',async(req,res)=>{const e=validOffer(req.body);if(e)return res.status(400).json({error:e});try{const x=req.body,r=await pool.query('INSERT INTO offers(title,subtitle,end_at,active) VALUES($1,$2,$3,$4) RETURNING *',[String(x.title).trim(),String(x.subtitle||'').trim(),new Date(x.end_at),x.active!==false]);res.status(201).json(r.rows[0])}catch(e){res.status(500).json({error:'Unable to create offer'})}});
app.put('/api/offers/:id',async(req,res)=>{try{const old=(await pool.query('SELECT * FROM offers WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Offer not found'});const x={...old,...req.body},e=validOffer(x);if(e)return res.status(400).json({error:e});const r=await pool.query('UPDATE offers SET title=$1,subtitle=$2,end_at=$3,active=$4 WHERE id=$5 RETURNING *',[String(x.title).trim(),String(x.subtitle||'').trim(),new Date(x.end_at),x.active!==false,req.params.id]);res.json(r.rows[0])}catch(e){res.status(500).json({error:'Unable to update offer'})}});
app.delete('/api/offers/:id',async(req,res)=>{try{const r=await pool.query('DELETE FROM offers WHERE id=$1',[req.params.id]);r.rowCount?res.json({ok:true}):res.status(404).json({error:'Offer not found'})}catch(e){res.status(500).json({error:'Unable to delete offer'})}});
app.post('/api/orders',async(req,res)=>{const{customer_name,email,phone='',address,items}=req.body;if(!String(customer_name||'').trim()||!String(email||'').trim()||!String(address||'').trim()||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Missing order information'});const client=await pool.connect();try{await client.query('BEGIN');let total=0;const rows=[];for(const i of items){const p=(await client.query('SELECT * FROM products WHERE id=$1 FOR UPDATE',[i.product_id])).rows[0];if(!p)throw new Error('Product not found');const qty=Number(i.qty),size=Number(i.size);if(!Number.isInteger(qty)||qty<1)throw new Error('Invalid quantity');if(!Number.isInteger(size)||!String(p.sizes).split(',').map(Number).includes(size))throw new Error(`Size ${i.size} is unavailable for ${p.name}`);if(p.stock<qty)throw new Error(`Insufficient stock for ${p.name}`);total+=p.price*qty;rows.push({p,qty,size})}const o=(await client.query('INSERT INTO orders(customer_name,email,phone,address,total) VALUES($1,$2,$3,$4,$5) RETURNING id',[String(customer_name).trim(),String(email).trim(),String(phone||'').trim(),String(address).trim(),total])).rows[0];for(const x of rows){await client.query('INSERT INTO order_items(order_id,product_id,size,qty,price) VALUES($1,$2,$3,$4,$5)',[o.id,x.p.id,x.size,x.qty,x.p.price]);await client.query('UPDATE products SET stock=stock-$1 WHERE id=$2',[x.qty,x.p.id])}await client.query('COMMIT');res.status(201).json({order_id:o.id,total})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/orders',async(req,res)=>{try{res.json((await pool.query(`SELECT o.*,COUNT(oi.id)::int AS item_count FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.id DESC`)).rows)}catch(e){res.status(500).json({error:'Unable to load orders'})}});
app.get('/api/orders/:id',async(req,res)=>{try{const r=await pool.query('SELECT id,customer_name,email,total,status,created_at FROM orders WHERE id=$1 AND lower(email)=lower($2)',[req.params.id,req.query.email||'']);r.rows[0]?res.json(r.rows[0]):res.status(404).json({error:'Order not found. Check order number and email.'})}catch(e){res.status(500).json({error:'Unable to load order'})}});
app.put('/api/orders/:id',async(req,res)=>{const allowed=['Pending','Confirmed','Shipped','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});try{const r=await pool.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);r.rowCount?res.json({ok:true}):res.status(404).json({error:'Order not found'})}catch(e){res.status(500).json({error:'Unable to update order'})}});
app.get('/api/stats',async(req,res)=>{try{res.json((await pool.query(`SELECT (SELECT COUNT(*) FROM products)::int AS products,(SELECT COUNT(*) FROM products WHERE stock<=5)::int AS "lowStock",(SELECT COUNT(*) FROM orders)::int AS orders,COALESCE((SELECT SUM(total) FROM orders WHERE status!='Cancelled'),0)::int AS revenue`)).rows[0])}catch(e){res.status(500).json({error:'Unable to load stats'})}});
app.get('/admin',(req,res)=>{if(!validToken(cookie(req,'sv_admin')))return res.redirect('/admin/login');res.sendFile(path.join(__dirname,'public','admin.html'))});
module.exports=app;if(require.main===module)ready.then(()=>app.listen(PORT,()=>console.log(`SoleVault running on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});